<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Purchase_iframe</name>
   <tag></tag>
   <elementGuidId>0e56aee7-af98-4e25-a44b-bc553f266275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ca5ab9d7-5871-4e76-941c-2ca93096ceab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>25d5f32c-eaa7-440f-b4b1-8cae529b722b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/</value>
      <webElementGuid>7bab19a3-5ada-430c-8e9e-38d70b3f3629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32a2ee60-d969-4924-8342-03c83a18bb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>df3c7291-f951-48ec-85c1-cf642684ee0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>468.666667px</value>
      <webElementGuid>a374a4a4-8b9b-4177-bda1-793e708653d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe&quot;)</value>
      <webElementGuid>9b1e7bc0-65a9-48f6-8ed5-548d679c7b18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='iframe']</value>
      <webElementGuid>94261555-ef89-48d0-bf26-958de03e73c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>33a05c41-670f-42cf-b91d-cb5f9a4ad488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe' and @src = 'https://modern-store.competethemes.com/']</value>
      <webElementGuid>0bab6dce-03ef-4b5c-ac82-c53cc42bb16d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
