<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded</name>
   <tag></tag>
   <elementGuidId>d1b2b3be-84f2-4af2-a465-ae8f469dbb8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.entry.product.type-product.post-332.status-publish.instock.product_cat-women.has-post-thumbnail.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail.entered.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loop-container']/ul/li[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7de9c4e5-b834-44ba-8ef9-eb9a73411539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>feb2a421-0344-4764-b5b9-107039064ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>74d0096e-15f4-4863-b796-74a358a86068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-300x300.jpg</value>
      <webElementGuid>4f8ddf72-32b7-4543-9091-c2ac3a4592df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded</value>
      <webElementGuid>0afb3084-829a-45a5-8be1-f3b6e0c4f156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>7c5b4b67-2aab-46a8-b7df-6fee9a15d974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-100x100.jpg 100w</value>
      <webElementGuid>3c5821ed-1831-4c95-b484-9e915dd54e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>20de2b1d-165e-49ee-8c1b-20fc6ab199bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-300x300.jpg</value>
      <webElementGuid>ee147ef6-3f75-4b63-8f53-dbca3c141f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>b299883c-5921-43a4-8d5f-fc7882891d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>06337818-461f-4bec-94c8-715dbad2ada3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-100x100.jpg 100w</value>
      <webElementGuid>ffebc53b-a94f-4f97-9355-06a9b9016941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loop-container&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;entry product type-product post-332 status-publish instock product_cat-women has-post-thumbnail shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded&quot;]</value>
      <webElementGuid>0a184e6b-c6d7-4a87-8b74-8db29c240c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Testcasemanually/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>f2d48180-78ce-44ed-b3e6-28271ca8bad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loop-container']/ul/li[2]/a/img</value>
      <webElementGuid>98c76030-2626-4a09-abd2-0bbfea2ba780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-300x300.jpg')]</value>
      <webElementGuid>f392433c-17ff-44f2-be4e-15004cb18343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>dfb14045-63b3-4c8a-b7fc-8ca51ff2b04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/womens-red-t-shirt-300x300.jpg']</value>
      <webElementGuid>0a88252f-060d-40db-8700-77b849b5e91e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
