<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_input</name>
   <tag></tag>
   <elementGuidId>26ef7499-db45-4269-a34a-f418af7dd0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8963731c-bf5b-4158-81bb-8e9c92a5378a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>35ab4425-7b08-438d-a7bf-f4fd2a83414f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ac7eede-3a87-410d-8413-77e908ad52dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb8484f9-632c-4702-86d7-6e17e7129267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>accounts.amount</value>
      <webElementGuid>c48ddeb2-fa0e-4c9f-9262-ebe70ebb562e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>72950996-5e61-4d1d-8ae1-65a275dc690b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount&quot;)</value>
      <webElementGuid>cbbe9578-c1ad-4ea1-b28e-d7ce2ddfad26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount']</value>
      <webElementGuid>b97ca732-9afc-4662-aa73-7a2b60b6ee3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/p/input</value>
      <webElementGuid>b8d242f3-aab6-48f4-b980-cf1ccd953995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a8298bc-a7dd-43ae-b6e3-e6bfb11ca179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount' and @type = 'text' and @name = 'input']</value>
      <webElementGuid>f4e572c6-2e67-41c2-bc46-6907f9ac6016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
