<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Close</name>
   <tag></tag>
   <elementGuidId>e56550da-518f-4fbc-8ff3-f188ebcfece2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ns-oq0mb-e-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dismiss-button']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f104877-fb66-4981-8d41-875fa002d282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ns-oq0mb-e-17</value>
      <webElementGuid>99e57093-575e-4576-b0c8-41745194a979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-overflow-forbidden</name>
      <type>Main</type>
      <value>xy</value>
      <webElementGuid>ec6ba5f2-3860-4131-b53e-da58048cc68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>1f91d875-f0dc-474e-ac4e-f28905cf7198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismiss-button&quot;)/div[@class=&quot;ns-oq0mb-e-17&quot;]</value>
      <webElementGuid>6b12ddf6-d6f3-4d5d-91bb-c5ae776a2135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Testing Demo Site  Practice Website Fo_343a98/iframe_Ad_ad_iframe</value>
      <webElementGuid>7958f1e2-1c61-4f89-830a-f96d0b3b6803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dismiss-button']/div</value>
      <webElementGuid>77b6bd52-50c3-460b-af71-6f5c202cdb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='worksoft.com'])[1]/following::div[3]</value>
      <webElementGuid>0390c765-c811-49ed-9970-bda784f60157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Worksoft Lets You Repurpose Your Process Automation toQuickly and Easily Move Automation'])[1]/following::div[8]</value>
      <webElementGuid>5c5b9b30-18c7-46cb-a062-ade35881b6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::div[2]</value>
      <webElementGuid>2b63276a-7870-4741-ba42-525d25fef43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>1aa615b7-a3f6-490b-9a88-b2316ec36d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>eb841473-0ce7-407b-a872-f3ccfbeea73a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
