<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_payee.phoneNumber</name>
   <tag></tag>
   <elementGuidId>bc5f9a93-9a8d-453e-9564-d9e7cfac54f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#12ef7fbe-e142-4b2f-a2f8-4718fdf4767a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='12ef7fbe-e142-4b2f-a2f8-4718fdf4767a']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2a2adbf-9549-41e3-a5ef-f156c7684dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12ef7fbe-e142-4b2f-a2f8-4718fdf4767a</value>
      <webElementGuid>03e739b9-1072-4554-9222-94abd5459d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input phone-number-12ef7fbe-e142-4b2f-a2f8-4718fdf4767a ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>292c34c3-867d-4280-b741-9e1cf200ce11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>b4783a3b-f7ee-4e81-ba55-bd3784095524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.phoneNumber</value>
      <webElementGuid>0d901a5c-b5b4-4f5c-ad6c-359c4108a648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;12ef7fbe-e142-4b2f-a2f8-4718fdf4767a&quot;)</value>
      <webElementGuid>d5a5b413-538c-4e61-85d6-a7719a988cf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='12ef7fbe-e142-4b2f-a2f8-4718fdf4767a']</value>
      <webElementGuid>debd71d7-72ac-4de9-af8e-30c5dfa0023d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>bbe385e2-b558-46e4-8313-b756ad4e4acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>7b34b1da-62ba-4bc5-b8ad-2cd04f94d2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '12ef7fbe-e142-4b2f-a2f8-4718fdf4767a' and @name = 'payee.phoneNumber']</value>
      <webElementGuid>b184bd26-1b80-447f-af24-fa9d71a97cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
