<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_payee.address.street</name>
   <tag></tag>
   <elementGuidId>112c5bdb-4926-404f-b2c6-551aab276941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;payee.address.street&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='payee.address.street']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcab6b79-15f4-43e2-a98c-8845bd1f8e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>09a7b3ed-426f-49a9-9d5c-36f6c1a90dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.address.street</value>
      <webElementGuid>c9e7750a-1941-4a5a-b934-a0cb82f4aa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.address.street</value>
      <webElementGuid>ecd569f7-60da-4eea-939f-4eb718b50f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[2]/td[2]/input[@class=&quot;input ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>1752fc74-237c-4de5-a7ce-780d8e6092f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='payee.address.street']</value>
      <webElementGuid>9e1765d1-2d4e-4e9d-8dfb-ca6f8600648e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>7c774751-e784-4241-b795-110230051fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>813dc765-43f7-44f9-b630-c03ea7c5c4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payee.address.street']</value>
      <webElementGuid>645b2aba-6a97-40ea-aa7a-f181af9f58bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
