<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_payee.address.city</name>
   <tag></tag>
   <elementGuidId>b33e2adf-661c-45a9-a412-2a16926d38ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;payee.address.city&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='payee.address.city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b75f3d4-9088-4904-bc14-5815feed7d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>a7d11e2d-4dc2-4865-a231-a29d95e11daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>payee.address.city</value>
      <webElementGuid>f981d32b-2f22-4767-8bfc-74a968074fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payee.address.city</value>
      <webElementGuid>b9a665a2-4a8e-49ac-9839-8be81c2ffce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[3]/td[2]/input[@class=&quot;input ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>bbff7073-37ef-49e9-b492-42747e6f49ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='payee.address.city']</value>
      <webElementGuid>07a98396-2d5a-4626-ab49-44f8cc96fa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>cf8a3201-423a-4c09-9748-b8b423956678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>6dec40b7-f51c-4ba2-82cb-4a0259062f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payee.address.city']</value>
      <webElementGuid>a491f486-d9ce-40df-95a2-824b590c9bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
