<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>06e7e72d-e5f2-4b26-9a61-3031a1eb86da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.card-footer-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Edit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be3f4928-e562-4383-b942-de9f2bbf9145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-footer-item</value>
      <webElementGuid>116570bb-6145-440d-8602-2477c11a2b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/edit</value>
      <webElementGuid>f70acf1c-5b5f-4dfc-8189-1b7c01b30e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>cd8fe760-0c09-469e-bb84-a1bde6b5dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/app-root[1]/app-test-site[1]/section[@class=&quot;hero has-background-white-ter&quot;]/div[@class=&quot;hero-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;columns is-multiline is-mobile&quot;]/div[@class=&quot;column is-3-desktop is-6-tablet&quot;]/app-menu[1]/div[@class=&quot;card&quot;]/footer[@class=&quot;card-footer&quot;]/a[@class=&quot;card-footer-item&quot;]</value>
      <webElementGuid>73fbbeeb-6f39-4b51-bd15-e90734df8786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit')]</value>
      <webElementGuid>e60b5b28-2ecd-4370-95a1-4997e2d9f791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interact with different types of input fields'])[1]/following::a[1]</value>
      <webElementGuid>881ce571-70c7-4251-bc45-662ceda2f42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Practice and become pro in test automation'])[1]/following::a[1]</value>
      <webElementGuid>5a526755-2aa0-4308-87c4-f4a0814ebd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interact with different types of buttons'])[1]/preceding::a[1]</value>
      <webElementGuid>0320b4f7-ecb8-4d23-8cb9-19dbd1b8fa98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click'])[1]/preceding::a[1]</value>
      <webElementGuid>5d6b2ea9-bce3-42e0-a9af-83dfbb1028ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>1ad0bc41-7909-460b-861c-817966a7e496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/edit')]</value>
      <webElementGuid>00d0d964-c7a8-447a-8349-ff52af1ce726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>b9761e38-8b13-48b7-8972-1f38b6a49d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/edit' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>24055011-f4f8-4cec-8623-bf7db227979e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
