<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , google_ads_iframe_24132379INTERSTITIAL_DemoGuru99_0, , ))_google_ads_iframe_24132379INTERSTITIAL_DemoGuru99_0</name>
   <tag></tag>
   <elementGuidId>fb3a85b9-bff3-4eae-8d97-5a3c85ae25cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0c861b12-f3a0-446f-9cf8-bc813c7ed2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0</value>
      <webElementGuid>88167961-48a9-49cb-a210-508319aca8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0</value>
      <webElementGuid>739abd76-f437-4c13-89c2-e62ccbc7bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>b77cef64-ba64-43f2-ae76-c5a1d58dea8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>defbd55c-c7aa-415e-84af-e5476d06a235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80428517-e6b8-4f0e-adf9-8b34d233a8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f983bb88-e789-46cb-8ce6-3bbff03ce5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92e23986-8e9b-43db-aaf3-cfa23a4f64a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>94a3edfc-0ded-4cbf-bae0-39f6442bdcb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>cdcd03ab-a81b-4cd4-b8ff-73fb4544cc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92a34bd0-bfb0-45d6-9245-c989baa7cf79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay</value>
      <webElementGuid>dc0d893c-2cae-4b39-a9a0-8708446c6e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3da60d59-5a5c-445d-87a7-af28e9f0a047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>432eb7fd-da1a-4c07-860c-1f26e6628519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0&quot;)</value>
      <webElementGuid>4905ea19-08da-4ffc-85e3-fd7899e9a503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0']</value>
      <webElementGuid>53d0a868-cd7d-4abb-913b-02434fb4aaf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0__container__']/iframe</value>
      <webElementGuid>e80bdaef-4366-4fae-994b-094724dbef16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>987d04de-e3ac-407c-91c2-d87eb7a89f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0' and @name = 'google_ads_iframe_/24132379/INTERSTITIAL_DemoGuru99_0' and @title = '3rd party ad content']</value>
      <webElementGuid>c48b2b78-6cd8-49f3-8348-351bbe0ccecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
