<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10.00</name>
   <tag></tag>
   <elementGuidId>1df8577a-9891-465a-9527-7712cbf7cf9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2327bbfe-928f-493a-9a11-174c09fac98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>4aae76e9-b053-4e90-b16c-4478ef2fa9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>bd826d61-2c51-4cff-b608-416ebdea1058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$10.00</value>
      <webElementGuid>50e45e33-b471-4d89-ad9f-448e5c36d064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount&quot;)</value>
      <webElementGuid>65fea174-9602-4a88-9f51-29eed11cbd8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='amount']</value>
      <webElementGuid>cb0efa73-b146-48eb-80e2-373b92c5cc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div[2]/p/span[2]</value>
      <webElementGuid>ea772049-d621-4bae-adf2-161f26c649e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nisha'])[1]/following::span[1]</value>
      <webElementGuid>d0221a45-ea12-4334-9e7b-f3611bc4ab06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Payment Complete'])[1]/following::span[2]</value>
      <webElementGuid>ac2221d1-75b0-40cd-93eb-7c22ca310adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error!'])[1]/preceding::span[2]</value>
      <webElementGuid>2ae5af92-38b9-4954-9c63-56b11055f485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$10.00']/parent::*</value>
      <webElementGuid>028880ae-6053-4aca-a421-f3c72e03c400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span[2]</value>
      <webElementGuid>02668207-4e71-46ce-a606-f0acc02a49e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'amount' and (text() = '$10.00' or . = '$10.00')]</value>
      <webElementGuid>9d98cfd2-21e3-4aef-bec2-698b627753df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
