<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1000.00</name>
   <tag></tag>
   <elementGuidId>3c5e0422-f696-4583-b87e-e0afd7795c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='accountTable']/tbody/tr[5]/td[2]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>b1da1ac8-22c0-4aad-aa99-1208aabc6d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>dafe6c76-02aa-44a0-aa12-a872baa9ced3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$1000.00</value>
      <webElementGuid>07c30e7e-fd67-4d48-a153-2c627a657a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountTable&quot;)/tbody[1]/tr[5]/td[2]/b[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>235d1cfb-f6c1-41c0-98ad-22516a0b3fee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='accountTable']/tbody/tr[5]/td[2]/b</value>
      <webElementGuid>eb7e3650-3335-412a-93d8-da3739d68331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::b[1]</value>
      <webElementGuid>385722c6-bcba-4eae-94fb-8ed1d02716d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$515.00'])[6]/following::b[2]</value>
      <webElementGuid>e8695d22-1b31-4003-a4b7-a284948f8b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*Balance includes deposits that may be subject to holds'])[1]/preceding::b[1]</value>
      <webElementGuid>e3739d48-9bd5-4c15-8c93-eaa7280a144b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$1000.00']/parent::*</value>
      <webElementGuid>6453437b-4846-4a11-bc27-b9b65a742fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/b</value>
      <webElementGuid>ae357863-c129-4afa-ac6c-a436df00a7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '$1000.00' or . = '$1000.00')]</value>
      <webElementGuid>c6c6a5f1-f963-4794-a5f6-49f9d477e816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
