<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_13899</name>
   <tag></tag>
   <elementGuidId>76defa02-739e-441d-bd7d-75a6923114bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newAccountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='newAccountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c208ed88-a81e-448d-8f67-2992f6cd194e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newAccountId</value>
      <webElementGuid>4992a5bd-415b-404f-b1d6-ef2515fa4ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>activity.htm?id=13899</value>
      <webElementGuid>c6e7ebc6-982b-4e27-b4a1-339bdfcef484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>73efea19-1f7e-4483-be4e-af086a6bd7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13899</value>
      <webElementGuid>3eb7783e-f03e-449c-8661-67daf77096c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newAccountId&quot;)</value>
      <webElementGuid>2c252e86-cd26-4fe8-83df-32fdcc503791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='newAccountId']</value>
      <webElementGuid>22ddf068-deb5-4e00-a9b0-35df633769a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/p[2]/a</value>
      <webElementGuid>ac9518d2-a33a-4d23-a5ac-045e0de4e40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'13899')]</value>
      <webElementGuid>f1d9953f-f433-4579-87dc-e5cb486e72fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your new account number:'])[1]/following::a[1]</value>
      <webElementGuid>7474deb6-ade7-4050-a04b-0cce1877d28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Opened!'])[1]/following::a[1]</value>
      <webElementGuid>27211b88-01f7-49ab-8c7c-95850f4b955a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[1]</value>
      <webElementGuid>79df1b9a-d078-4d78-af62-a8ad77058173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13899']/parent::*</value>
      <webElementGuid>cfd095ad-48fb-40cd-b64e-cda32337129c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'activity.htm?id=13899')]</value>
      <webElementGuid>ccfe60c7-6c74-45d7-9928-d962c7116066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>999cd293-7e55-43f9-a874-b4bfe5e8f4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'newAccountId' and @href = 'activity.htm?id=13899' and (text() = '13899' or . = '13899')]</value>
      <webElementGuid>9e2f7c91-105d-40b6-b2b0-d008f352c1d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
