<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__attachment-woocommerce_thumbnail size-_691320</name>
   <tag></tag>
   <elementGuidId>75bc9200-dbe7-4858-aa66-8e1079f7d8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loop-container']/ul/li[9]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.entry.product.type-product.post-306.status-publish.first.instock.product_cat-women.has-post-thumbnail.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail.entered.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d2d487ef-4181-4e6a-bf23-673bbc37b2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b48224f6-2f06-4fe0-9905-0c92ca07e8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>fcc6e785-cd42-4a8a-bcf7-30c65aee5903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-300x300.jpg</value>
      <webElementGuid>96b59623-d888-4f8f-a7ba-42b398cb3481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded</value>
      <webElementGuid>1262356b-ea28-4c19-980c-ce206b9c0413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>409f6b45-2212-46e1-b9be-d78ee8b0506c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-100x100.jpg 100w</value>
      <webElementGuid>26bac7ac-69b2-4156-bf78-a658ad24c342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>2e2c3c7f-df4b-407d-9445-daf855709311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lazy-src</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-300x300.jpg</value>
      <webElementGuid>35c03a2b-0e77-48b5-b379-a9b067b2e053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ll-status</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>ca6954f0-95a1-4e63-9f97-1b22e109aff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 300px) 100vw, 300px</value>
      <webElementGuid>a854c29e-5b4d-4d3a-86d5-d071c4534602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-300x300.jpg 300w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-600x600.jpg 600w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-150x150.jpg 150w, https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-100x100.jpg 100w</value>
      <webElementGuid>9b4f4d09-4235-489f-a2d0-582ee6250a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loop-container&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;entry product type-product post-306 status-publish first instock product_cat-women has-post-thumbnail shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail entered lazyloaded&quot;]</value>
      <webElementGuid>df69d47a-c7cb-476f-aab7-1ea8e84b9660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Demo Site/iframe_Purchase_iframe</value>
      <webElementGuid>4530b4b3-56d1-466f-8bd0-26b3abdd5fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loop-container']/ul/li[9]/a/img</value>
      <webElementGuid>456d42f9-91e6-4ded-80a5-974f521d7fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-300x300.jpg')]</value>
      <webElementGuid>00453f5f-1bb5-470d-a32d-cbac5e913a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/img</value>
      <webElementGuid>97a17bc8-693a-4a04-abe1-a60716f8c014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://modern-store.competethemes.com/wp-content/uploads/sites/60/2019/05/attractive-beautiful-beauty-1171849-300x300.jpg']</value>
      <webElementGuid>e83f1bc1-319a-4e8a-8371-17803e603a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
