<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clear the text_clearMe</name>
   <tag></tag>
   <elementGuidId>028f1489-b7a9-45ad-b1b2-6949fdf4bb4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clearMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3040db7f-8d8e-48bd-8932-bdb37f97b698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearMe</value>
      <webElementGuid>ce9ab362-6960-4eab-bfb2-1fdb07c1fd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Koushik Chatterjee</value>
      <webElementGuid>d8a10b39-6a6c-440f-b8b6-f28fb025ac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50c839df-0d97-4d2b-a3cc-9d826544515a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter </value>
      <webElementGuid>7c1ce7c0-6b4d-4f5f-8c13-218057b3b3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>503924ad-b16f-4302-8600-09c94d9c160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearMe&quot;)</value>
      <webElementGuid>78f52eda-924b-42ae-9132-3f0032b59372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clearMe']</value>
      <webElementGuid>2be5fdfa-4e46-4da8-b7e1-ff9e244848a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>c7f6105a-3033-4384-b3c5-0c01a42667af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clearMe' and @type = 'text' and @placeholder = 'Enter ']</value>
      <webElementGuid>1994e854-c753-4c01-8e55-72aa3dd62b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
