<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What is inside the text box_getMe</name>
   <tag></tag>
   <elementGuidId>c6263fc2-49e2-418e-8a98-37934bfc241b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#getMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='getMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d19b30f3-c1be-4da3-bc95-20fdcc7b8cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>getMe</value>
      <webElementGuid>189bd97d-5657-4bd3-9b1c-9db583a58708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ortonikc</value>
      <webElementGuid>14cd03a5-3518-4058-988b-8c0e362c7406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd14c405-ec76-435f-b795-264aac3a94d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter </value>
      <webElementGuid>dc15cc5c-4b42-46d7-89a6-886bf4ceeecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac35656a-ce8c-403a-b095-79839cf93342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getMe&quot;)</value>
      <webElementGuid>3b104cb4-5d03-4418-bdf9-a83e411679fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='getMe']</value>
      <webElementGuid>d85d5f8b-e919-475a-a559-0f1745f1d3dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c9bbcdd5-ed5a-4690-8003-cad827bbb524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'getMe' and @type = 'text' and @placeholder = 'Enter ']</value>
      <webElementGuid>dd5ac44a-eec6-41e9-86c0-a1493a58fe95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
