<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Append a text and press keyboard tab_join</name>
   <tag></tag>
   <elementGuidId>a7915612-65ab-488b-9f7f-5deabe40649b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#join</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='join']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f34d972d-f4c8-4779-934e-0412a9e7e252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>join</value>
      <webElementGuid>2786a307-396e-442c-bd4f-1809ea05af1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I am good</value>
      <webElementGuid>5b6d7ad8-c013-4825-83cb-29808c6364cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79ab5ffe-fd1e-46c0-9d09-68c5f04f6496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter </value>
      <webElementGuid>91e050bd-02a0-426f-a8c7-5c77851b4673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b9a824d-14e0-45ca-ae5e-65ab79aef44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;join&quot;)</value>
      <webElementGuid>a1725f73-5083-4004-82c9-bc81ac93dbf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='join']</value>
      <webElementGuid>4e3026b2-60ba-4259-8e27-3bc38f0844ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>1d295412-9d30-4542-9fca-02b9d5498c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'join' and @type = 'text' and @placeholder = 'Enter ']</value>
      <webElementGuid>55a7c627-7aee-4234-8a70-72a4750c78f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
