<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm edit field is disabled_noEdit</name>
   <tag></tag>
   <elementGuidId>caee34ba-61c9-4191-a26d-c2f7e9ad2a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noEdit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noEdit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0310761c-34ec-4b83-b64d-33172e241620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noEdit</value>
      <webElementGuid>9d49b296-5847-4611-a65a-0fe3549a6c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07c9a26a-281b-43c9-ba96-02bbd3c60bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>87e8f6c0-2fe1-42a4-a227-9e83c52035a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fb3bb16-539e-47ac-a9a3-271d43ab9d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noEdit&quot;)</value>
      <webElementGuid>dbc28e18-2f37-449b-b1e9-e28f7bdab2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noEdit']</value>
      <webElementGuid>d2c3fdaa-9823-4bce-9d91-533b25b77862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>4b8e5f8f-de83-4ba3-a75b-9cdf217bb252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'noEdit' and @type = 'text' and @placeholder = 'Enter']</value>
      <webElementGuid>87fb792a-ddd3-4ffe-9152-cdfb43990561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
