<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm text is readonly_dontwrite</name>
   <tag></tag>
   <elementGuidId>b443c88b-5244-4df2-9073-265d375c75e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dontwrite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dontwrite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e82856f0-69de-4892-ae5c-1843bc9a0ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dontwrite</value>
      <webElementGuid>b34e9e8d-e924-460e-9d9b-a834c884f636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>19cc613e-0ddc-4c51-8d1d-d6b1dbdc868a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>This text is readonly</value>
      <webElementGuid>bd636a33-f183-47e1-b369-087003e3743a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf37600b-9f1f-4017-808c-ee93c463590f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dontwrite&quot;)</value>
      <webElementGuid>019bacc8-239a-47cc-801c-5f668b04c02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dontwrite']</value>
      <webElementGuid>1ad57690-a00a-4202-84ea-3fbe76c27b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>fe55c14d-b3e2-4c99-984e-58b1152e8ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dontwrite' and @type = 'text']</value>
      <webElementGuid>6ba3af1a-f1f5-4378-a4f8-161433d32276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
